# building of sample applications
SAMPLE_CXX_SIMU_SRC= \
	samples/main-forwarding-simulator.cc \
	$(NULL)
SAMPLE_CXX_SIMU_OUTPUT=$(call gen-bin, $(basename $(SAMPLE_CXX_SIMU_SRC)))
SAMPLE_CXX_SIMU_CXXFLAGS=$(CXXFLAGS)
SAMPLE_CXX_SIMU_LDFLAGS=$(LDFLAGS) -L$(TOP_BUILD_DIR) -lyans

SAMPLE_CXX_SIMUTEMP_SRC= \
	samples/main-forwarding-simulator-template.cc \
	$(NULL)
SAMPLE_CXX_SIMUTEMP_OUTPUT=$(call gen-bin, $(basename $(SAMPLE_CXX_SIMUTEMP_SRC)))
SAMPLE_CXX_SIMUTEMP_CXXFLAGS=$(CXXFLAGS)
SAMPLE_CXX_SIMUTEMP_LDFLAGS=$(LDFLAGS) -L$(TOP_BUILD_DIR) -lyans

SAMPLE_CXX_SIMPLE_SRC= \
	samples/main-simple.cc \
	$(NULL)
SAMPLE_CXX_SIMPLE_OUTPUT=$(call gen-bin, $(basename $(SAMPLE_CXX_SIMPLE_SRC)))
SAMPLE_CXX_SIMPLE_CXXFLAGS=$(CXXFLAGS)
SAMPLE_CXX_SIMPLE_LDFLAGS=$(LDFLAGS) -L$(TOP_BUILD_DIR) -lyans

SAMPLE_CXX_ROUTER_SRC= \
	samples/main-router.cc \
	$(NULL)
SAMPLE_CXX_ROUTER_OUTPUT=$(call gen-bin, $(basename $(SAMPLE_CXX_ROUTER_SRC)))
SAMPLE_CXX_ROUTER_CXXFLAGS=$(CXXFLAGS)
SAMPLE_CXX_ROUTER_LDFLAGS=$(LDFLAGS) -L$(TOP_BUILD_DIR) -lyans

SAMPLE_CXX_TCP_SRC= \
	samples/main-tcp.cc \
	$(NULL)
SAMPLE_CXX_TCP_OUTPUT=$(call gen-bin, $(basename $(SAMPLE_CXX_TCP_SRC)))
SAMPLE_CXX_TCP_CXXFLAGS=$(CXXFLAGS)
SAMPLE_CXX_TCP_LDFLAGS=$(LDFLAGS) -L$(TOP_BUILD_DIR) -lyans

SAMPLE_CXX_THREAD_SRC= \
	samples/main-thread.cc \
	$(NULL)
SAMPLE_CXX_TREAD_OUTPUT=$(call gen-bin, $(basename $(SAMPLE_CXX_THREAD_SRC)))
SAMPLE_CXX_TREAD_CXXFLAGS=$(CXXFLAGS)
SAMPLE_CXX_TREAD_LDFLAGS=$(LDFLAGS) -L$(TOP_BUILD_DIR) -lyans

ALL += \
	SAMPLE_CXX_SIMPLE \
	SAMPLE_CXX_ROUTER \
	SAMPLE_CXX_TCP \
	SAMPLE_CXX_SIMU \
	SAMPLE_CXX_SIMUTEMP \
	SAMPLE_CXX_THREAD \
	SAMPLES_MK \
	$(NULL)
